want to see all data

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -78,16 +78,16 @@ jobs:
               --instance-id ${{ env.INSTANCE_ID_1 }} || true
         - name: Get Docker Command Output
           run: |
-            ssm_command_output=$(aws ssm list-commands --command-id ${{ env.command_id }} --query 'Commands[0].Status' --output text)
+            ssm_command_output=$(aws ssm list-commands --command-id ${{ env.command_id }})
 
             echo "$ssm_command_output"
 
-            echo "status=$ssm_command_output" >> $GITHUB_ENV
-        - name: Check Docker Command Status
-          run: |
-            if [[ "${{ env.status }}" == "Success" ]]; then
-              echo "Docker operations completed successfully"
-            else
-              echo "Docker operations failed"
-              exit 1
-            fi
+        #     echo "status=$ssm_command_output" >> $GITHUB_ENV
+        # - name: Check Docker Command Status
+        #   run: |
+        #     if [[ "${{ env.status }}" == "Success" ]]; then
+        #       echo "Docker operations completed successfully"
+        #     else
+        #       echo "Docker operations failed"
+        #       exit 1
+        #     fi
