Test

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -56,7 +56,7 @@ jobs:
             INSTANCE_ID_2: ${{ secrets.INSTANCE_ID_2 }}
           run: |
             echo "$ECR_IMAGE_TO_DEPLOY"
-            aws ssm send-command \
+            command_id=$(aws ssm send-command \
               --targets Key=InstanceIds,Values=${{ env.INSTANCE_ID_1 }},${{ env.INSTANCE_ID_2 }} \
               --document-name "AWS-RunShellScript" \
               --comment "Executing Docker operations" \
@@ -65,7 +65,21 @@ jobs:
                   "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_IMAGE_TO_DEPLOY }}",
                   "docker pull $ECR_IMAGE_TO_DEPLOY",
                   "docker run -d -p 3000:3000 --name ${{ secrets.CONTAINER_NAME }} $ECR_IMAGE_TO_DEPLOY"
-              ]'
+              ]' --query 'Command.CommandId' --output text)
+              echo "command_id=$command_id" >> $GITHUB_ENV
+        - name: Retrieve and Store SSM Command Results
+          run: |
+            aws ssm wait command-executed \
+              --command-id ${{ env.command_id }} \
+              --instance-id ${{ env.INSTANCE_ID_1 }} || true
+            ssm_command_output=$(aws ssm get-command-invocation \
+                --command-id ${{ env.command_id }} \
+                --instance-id ${{ env.INSTANCE_ID_1 }})
+            standard_error_content=$(echo "$ssm_command_output" | jq -r '.StandardErrorContent')
+            standard_error_content=${standard_error_content//$'\n'/' '}
+            status=$(echo "$ssm_command_output" | jq -r '.Status')
+            echo "status=$status" >> $GITHUB_ENV
+            echo "standard_error_content=$standard_error_content" >> $GITHUB_ENV
 
         # - name: Execute Docker Commands on AWS Instance to deploy the application
         #   env:
